import {useState} from "react";
import {AlertTriangle,ArrowRight,Check,ChevronRight,Eye,KeyRound,LockKeyhole,MessageCircleWarning,RotateCcw,ShieldCheck,Smartphone,UserRoundX,X} from "lucide-react";

const questions=[
 {channel:"Mensaje",from:"Aviso de cuenta",text:"Su cuenta será suspendida. Abra el siguiente enlace para seguir disfrutando de nuestro contenido.",prompt:"¿Qué haces?",options:["Abro el enlace para evitar que suspendan mi cuenta.","Reviso quién envió el mensaje y después decido si abrirlo.","No abro el enlace; ingreso directamente a la aplicación o página oficial para revisar mi cuenta."],scores:[2,1,0],correct:2,why:"Los mensajes que amenazan con suspender una cuenta buscan que actúes con prisa. Entra siempre desde la aplicación o página oficial."},
 {channel:"WhatsApp o audio",from:"Número desconocido",text:"Hola, hijo/a. Me prestaron este celular. ¿Me puedes hacer una transferencia, por favor? Es urgente.",prompt:"¿Qué haces?",options:["Lo llamo a su número conocido o contacto a otro familiar para verificar la situación.","Realizo la transferencia porque reconozco su voz.","Le hago algunas preguntas por mensaje para confirmar su identidad."],scores:[0,2,1],correct:0,why:"Una voz también puede ser imitada o generada. Verifica la solicitud por un número conocido o con otro familiar."},
 {channel:"Contraseña",from:"Nueva cuenta",text:"Debes crear una contraseña nueva.",prompt:"¿Cuál elegirías?",options:["MiPerrito34","J!7p%H@2k&Z","12345678"],scores:[1,0,2],correct:1,why:"Una contraseña larga, impredecible y diferente para cada cuenta reduce el riesgo de que alguien pueda adivinarla o reutilizarla."},
 {channel:"Correo",from:"Aviso de premio",text:"Ganaste un premio. Para recibirlo debes proporcionar tu nombre, dirección y una cuenta bancaria para depositar el dinero.",prompt:"¿Qué haces?",options:["Envío los datos porque quiero recibir el premio.","Busco el nombre de la empresa en internet antes de responder.","No comparto información y verifico la promoción directamente en los canales oficiales de la empresa."],scores:[2,1,0],correct:2,why:"Los premios inesperados suelen utilizarse como señuelo para obtener datos. Verifica siempre desde los canales oficiales."},
 {channel:"Llamada",from:"Supuesto banco",text:"Debemos actualizar tus datos bancarios. Dime el código que acaba de llegar a tu celular para completar la actualización.",prompt:"¿Qué haces?",options:["No comparto el código, cuelgo y llamo directamente al número oficial del banco.","Le proporciono el código para terminar la actualización.","Le pregunto su nombre y número de empleado antes de continuar."],scores:[0,2,1],correct:0,why:"Los códigos de verificación son secretos. Ningún empleado necesita que se los dictes para actualizar tus datos."},
 {channel:"Aplicación",from:"Filtros divertidos",text:"La aplicación solicita acceso a tus contactos, galería, micrófono y ubicación.",prompt:"¿Qué haces?",options:["Acepto los permisos y pienso revisarlos después.","Reviso para qué necesita cada permiso y autorizo únicamente los indispensables.","Acepto todos los permisos para poder utilizar los filtros."],scores:[1,0,2],correct:1,why:"Los permisos dan acceso a información sensible. Autoriza únicamente aquellos que sean necesarios para la función que usarás."},
 {channel:"WhatsApp",from:"Uno de tus contactos",text:"Te envié por error un código de seis dígitos. ¿Me lo puedes mandar?",prompt:"¿Qué haces?",options:["Se lo envío porque el mensaje viene de uno de mis contactos.","Le pregunto para qué necesita el código antes de decidir.","No comparto el código y contacto a la persona por otro medio para avisarle que su cuenta podría haber sido robada."],scores:[2,1,0],correct:2,why:"Ese código podría permitir que otra persona registre tu cuenta de WhatsApp en otro dispositivo. Nunca lo compartas."},
 {channel:"Seguridad de cuenta",from:"Configuración",text:"Una de tus cuentas ofrece activar la verificación en dos pasos.",prompt:"¿Qué decides?",options:["La activo para añadir una segunda barrera de seguridad.","No la activo porque tarda más iniciar sesión.","La dejo para después."],scores:[0,2,1],correct:0,why:"La verificación en dos pasos dificulta el acceso incluso si alguien consigue tu contraseña."},
 {channel:"Soporte técnico",from:"Supuesto técnico",text:"Instala esta aplicación para que pueda controlar tu teléfono a distancia y solucionar el problema.",prompt:"¿Qué haces?",options:["Busco rápidamente el nombre de la aplicación antes de instalarla.","No la instalo y contacto directamente al soporte oficial.","La instalo y sigo sus instrucciones."],scores:[1,0,2],correct:1,why:"El acceso remoto puede permitir que alguien vea tu pantalla, datos y aplicaciones. Contacta al soporte desde su canal oficial."},
 {channel:"Notificación",from:"Inicio de sesión",text:"Se detectó un inicio de sesión que no reconoces.",prompt:"¿Qué haces?",options:["La ignoro; quizá fue un error.","Reviso la cuenta cuando tenga tiempo.","Cambio la contraseña inmediatamente, cierro las sesiones abiertas y activo la verificación en dos pasos."],scores:[2,1,0],correct:2,why:"Un acceso desconocido requiere actuar de inmediato para recuperar el control y cerrar la puerta al intruso."}
];

const signals=[
 {number:"01",icon:AlertTriangle,title:"Robo de una cuenta mediante un enlace falso",attack:"Envía un mensaje que amenaza con suspender tu cuenta y coloca un enlace que imita la página oficial.",consequence:"Puede robar tu usuario y contraseña, entrar a tu cuenta y cambiar los datos de recuperación para dejarte sin acceso.",action:"No abras el enlace. Entra directamente a la aplicación o página oficial."},
 {number:"02",icon:MessageCircleWarning,title:"Suplantación de un familiar para robar dinero",attack:"Escribe desde otro número, crea una historia urgente e incluso puede imitar la voz de alguien cercano.",consequence:"Puedes transferir dinero al delincuente y compartir datos que después utilizará para engañarte nuevamente.",action:"Llama al número que ya conoces o verifica la situación con otro familiar."},
 {number:"03",icon:KeyRound,title:"Acceso a varias cuentas por una contraseña débil",attack:"Prueba contraseñas comunes, datos relacionados contigo o claves filtradas en otros servicios.",consequence:"Puede entrar a tu correo, redes sociales o tiendas y utilizar esas cuentas para robar información o suplantar tu identidad.",action:"Crea contraseñas largas, impredecibles y diferentes para cada cuenta."},
 {number:"04",icon:Eye,title:"Robo y uso indebido de tus datos personales",attack:"Promete un premio o beneficio y solicita tu nombre, dirección, teléfono o información bancaria.",consequence:"Tus datos pueden utilizarse para cometer fraudes, abrir cuentas a tu nombre, enviarte engaños más creíbles o intentar robar tu identidad.",action:"No compartas información. Confirma la promoción en los canales oficiales."},
 {number:"05",icon:LockKeyhole,title:"Robo de dinero mediante una llamada falsa",attack:"Se hace pasar por personal del banco, te alarma con un supuesto problema y pide el código que llegó a tu celular.",consequence:"Con ese código puede autorizar operaciones, entrar a tu banca digital o realizar movimientos sin tu permiso.",action:"No compartas el código. Cuelga y llama al número oficial del banco."},
 {number:"06",icon:Smartphone,title:"Uso indebido de información por una aplicación",attack:"Ofrece una función atractiva, pero solicita acceso innecesario a contactos, fotos, micrófono y ubicación.",consequence:"La aplicación podría recopilar, compartir o utilizar tu información y la de tus contactos sin que seas plenamente consciente.",action:"Revisa cada permiso y autoriza únicamente los indispensables."},
 {number:"07",icon:MessageCircleWarning,title:"Robo de WhatsApp y suplantación de identidad",attack:"Desde la cuenta de un contacto pide el código de seis dígitos que llegó a tu celular y dice que fue enviado por error.",consequence:"Puede apoderarse de tu WhatsApp, leer conversaciones y hacerse pasar por ti para pedir dinero o información a tus contactos.",action:"Nunca compartas el código y avisa a tu contacto por otro medio."},
 {number:"08",icon:ShieldCheck,title:"Ingreso a tu cuenta después de robar la contraseña",attack:"Consigue tu clave mediante una filtración, un engaño o una página falsa e intenta utilizarla inmediatamente.",consequence:"Si no existe una segunda barrera, puede entrar, consultar información privada y tomar el control de la cuenta.",action:"Activa la verificación en dos pasos en tus cuentas importantes."},
 {number:"09",icon:UserRoundX,title:"Control remoto y robo desde tu dispositivo",attack:"Se presenta como técnico y te convence de instalar una aplicación que le permite manejar tu teléfono a distancia.",consequence:"Puede ver contraseñas y códigos, abrir aplicaciones bancarias, copiar archivos o realizar operaciones mientras observa tu pantalla.",action:"No instales nada. Comunícate directamente con el soporte oficial."},
 {number:"10",icon:AlertTriangle,title:"Toma de control de una cuenta",attack:"Entra con credenciales robadas y espera que ignores o retrases la alerta de inicio de sesión.",consequence:"Puede cambiar tu contraseña, cerrar tus sesiones, acceder a información privada y usar tu cuenta para defraudar a otras personas.",action:"Cambia tu contraseña, cierra las sesiones abiertas y activa la verificación en dos pasos."}
];

const habits=[
 {icon:KeyRound,title:"Contraseñas diferentes",text:"Usa una clave única y difícil de adivinar para cada cuenta importante."},
 {icon:ShieldCheck,title:"Verificación en dos pasos",text:"Actívala y nunca compartas los códigos que recibas."},
 {icon:Eye,title:"Pausa antes de abrir",text:"Revisa remitente, dirección, enlaces y archivos antes de tocarlos."},
 {icon:UserRoundX,title:"Datos bajo control",text:"Evita publicar ubicación, documentos, teléfonos o información financiera."},
 {icon:Smartphone,title:"Equipos actualizados",text:"Instala actualizaciones de aplicaciones y del sistema operativo."}
];

export default function Home(){
 const[started,setStarted]=useState(false),[current,setCurrent]=useState(0),[selected,setSelected]=useState<number|null>(null),[points,setPoints]=useState(0),[done,setDone]=useState(false),[slide,setSlide]=useState(0);
 const q=questions[current];
 function choose(i:number){if(selected!==null)return;setSelected(i);setPoints(p=>p+q.scores[i])}
 function next(){if(current===questions.length-1)setDone(true);else{setCurrent(n=>n+1);setSelected(null)}}
 function restart(){setCurrent(0);setPoints(0);setSelected(null);setDone(false);setStarted(true)}
 const result=points<=5
  ?{icon:"🛡️",title:"Escudo digital",risk:"Tu nivel de riesgo es bajo",text:"Sabes reconocer muchas señales de peligro. Sueles verificar la información antes de actuar, proteges tus cuentas y evitas compartir datos o códigos sin confirmar quién los solicita.",advice:"Continúa utilizando contraseñas diferentes, activa la verificación en dos pasos y mantente alerta ante nuevas formas de fraude."}
  :points<=12
  ?{icon:"⚠️",title:"Alerta preventiva",risk:"Tu nivel de riesgo es moderado",text:"Tienes algunos buenos hábitos de seguridad, pero la confianza, el miedo o la urgencia podrían llevarte a tomar una decisión riesgosa.",advice:"Antes de abrir un enlace, transferir dinero o compartir información, detente y verifica la solicitud directamente con la persona o institución involucrada."}
  :{icon:"🚨",title:"Riesgo elevado",risk:"Tu nivel de riesgo es alto",text:"Tus hábitos actuales podrían facilitar que un ciberdelincuente robe tu información, ingrese a tus cuentas o te convenza de realizar una transferencia.",advice:"No compartas códigos de verificación, evita reutilizar contraseñas y desconfía de los mensajes que te presionen para actuar inmediatamente."};
 const selectedScore=selected===null?null:q.scores[selected];
 const feedback=selectedScore===2?"Esta respuesta aumenta tu nivel de riesgo.":selectedScore===1?"Es una precaución útil, pero todavía existe riesgo.":"Esta es la acción más segura.";
 return <main>
  <header className="topbar"><a className="brand" href="#inicio"><span className="brand-mark"><LockKeyhole size={20}/></span><span>Protege tu <b>vida digital</b></span></a><nav aria-label="Navegación principal"><a href="#materiales">Recursos</a><a href="#quiz">Quiz</a><a href="#senales">Detecta estafas</a><a className="nav-quiz" href="#habitos">Protégete</a></nav></header>
  <section className="hero" id="inicio">
   <div className="hero-copy"><p className="material-tag">RECURSO 1 DE 4 · BANNER DIGITAL</p><p className="eyebrow"><span/>Tu información vale. Protégela.</p><h1>Un clic bastó para perder <em>$18,000.</em></h1><p className="lead">El enlace parecía real. Usaron la urgencia para obtener sus datos bancarios. <b>Que no te pase:</b> aprende a reconocer la manipulación antes de actuar.</p><a className="primary" href="#materiales">Conoce cómo protegerte <ArrowRight size={20}/></a><p className="safe-note"><ShieldCheck size={17}/>Detente. Verifica. Protege.</p></div>
   <div className="hero-visual" aria-label="Ejemplo de mensaje sospechoso"><div className="pulse pulse-one"/><div className="pulse pulse-two"/><div className="phone"><div className="phone-top"><span>10:24</span><span>● ● ●</span></div><div className="chat-head"><div className="avatar">BS</div><div><b>Banco Seguridad</b><small>Cuenta empresarial</small></div></div><div className="bubble">Detectamos un cargo inusual. Confirma tus datos <u>ahora</u> para evitar el bloqueo.<small>10:23 ✓✓</small></div><div className="warning-label"><AlertTriangle size={18}/>La urgencia busca que actúes sin pensar</div></div></div>
  </section>
  <section className="purpose" id="materiales"><div><p className="kicker">Ingeniería social</p><h2>No atacan primero al dispositivo.<br/>Intentan manipularte a ti.</h2></div><div><p>Los delincuentes pueden hacerse pasar por tu banco, una autoridad, una empresa o incluso un familiar. Buscan provocar <b>urgencia, temor o confianza</b> para que abras un enlace, compartas información personal o transfieras dinero.</p><p className="purpose-rule"><AlertTriangle size={22}/><span>Si un mensaje altera tus emociones, <b>haz una pausa antes de actuar.</b></span></p></div></section>
  <section className="materials-map" aria-label="Recursos de la campaña"><p>Esta campaña busca que conozcas mejor tu seguridad digital y puedas navegar de una manera más segura.</p><div><a href="#inicio"><span>01</span>Banner</a><a href="#quiz"><span>02</span>¿Qué tan fácil sería engañarte?</a><a href="#senales"><span>03</span>Señales de que estás frente a una estafa digital</a><a href="#habitos"><span>04</span>5 hábitos para proteger tu información</a></div></section>

  <section className="quiz-section" id="quiz"><div className="section-intro"><p className="material-tag light">RECURSO 2 DE 4 · QUIZ DE EVALUACIÓN</p><h2>¿Qué tan fácil sería engañarte?</h2><p>Los ciberdelincuentes pueden aprovechar la confianza, el miedo o la urgencia para obtener información personal, ingresar a tus cuentas o robar tu dinero.</p><p>Responde con sinceridad estas 10 situaciones y descubre qué tan protegida está tu vida digital.</p></div>
   <div className="quiz-shell">
   {!started?<div className="quiz-welcome"><div className="big-shield"><ShieldCheck size={58}/></div><div><span className="mini-label">10 SITUACIONES · 0 A 20 PUNTOS</span><h3>Tu mejor defensa comienza con una pausa</h3><p>Lee cada situación y elige la respuesta que más se parezca a lo que harías. Responde con sinceridad para obtener un resultado útil.</p><button className="primary" onClick={()=>setStarted(true)}>Iniciar quiz <ChevronRight size={21}/></button></div></div>
   :done?<div className="result"><div className="score-ring"><strong>{points}</strong><span>de 20</span></div><p className="mini-label">TU RESULTADO</p><div className="result-icon">{result.icon}</div><h3>{result.title}</h3><h4>{result.risk}</h4><p>{result.text}</p><p>{result.advice}</p><div className="result-rule"><b>Regla de oro</b><span>Detente. Verifica. Protege.</span><p>Si un mensaje te pide actuar inmediatamente, abrir un enlace, enviar dinero o compartir información, comunícate directamente con la persona o institución mediante un canal oficial.</p><strong>Tu información vale. Protege tu vida digital.</strong></div><div className="survey"><p className="mini-label">TU OPINIÓN TAMBIÉN PROTEGE</p><h3>Ayúdanos a mejorar esta campaña</h3><p>Comparte tu experiencia y cuéntanos qué te pareció. Te tomará menos de un minuto.</p><iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdVlpiZOhdv8jcaMHseabzMs9kikyS7ddIJCNGBT2aLJzG4Hg/viewform?embedded=true" title="Formulario de comentarios sobre la campaña" loading="lazy">Cargando…</iframe></div><button className="secondary" onClick={restart}><RotateCcw size={19}/>Volver a intentarlo</button></div>
   :<div className="question-view"><div className="quiz-progress"><span>Situación {current+1} de {questions.length}</span><div><i style={{width:`${((current+1)/questions.length)*100}%`}}/></div></div><div className="message-card"><div className="message-meta"><span><MessageCircleWarning size={18}/>{q.channel}</span><small>{q.from}</small></div><p>“{q.text}”</p></div><h3>{q.prompt}</h3><div className="answers">{q.options.map((option,i)=><button key={option} className={selected===null?"":i===q.correct?"correct":i===selected?"wrong":"muted"} onClick={()=>choose(i)} disabled={selected!==null}><span>{String.fromCharCode(65+i)}</span>{option}{selected!==null&&i===q.correct?<Check size={20}/>:selected===i&&i!==q.correct?<X size={20}/>:null}</button>)}</div>{selected!==null&&<div className={`feedback ${selectedScore===0?"good":"care"}`}><b>{feedback}</b><p>{q.why}</p><small>Esta respuesta suma {selectedScore} {selectedScore===1?"punto":"puntos"} de riesgo.</small><button onClick={next}>{current===questions.length-1?"Ver mi resultado":"Siguiente situación"}<ArrowRight size={18}/></button></div>}</div>}
   </div>
  </section>

  <section className="signals" id="senales"><div className="section-intro left"><p className="material-tag">RECURSO 3 DE 4 · CARRUSEL INFORMATIVO</p><p className="kicker">Situaciones que pueden afectar tu vida digital</p><h2>Señales de que estás frente a una estafa digital</h2><p>Conoce cómo actúan los delincuentes, qué consecuencias puede tener caer en la trampa y cómo protegerte.</p></div><div className="carousel">
   {signals.map(({number,icon:Icon,title,attack,consequence,action},i)=><article key={title} className={i===slide?"active":""} aria-hidden={i!==slide}><div className="slide-count">{number} / 10</div><div className="slide-icon"><Icon/></div><h3>{title}</h3><div className="threat-block"><b>Lo que hace el atacante</b><p>{attack}</p></div><div className="consequence-block"><b>Si caes en la trampa</b><p>{consequence}</p></div><div className="slide-action"><ShieldCheck size={23}/><span><b>Qué hacer:</b> {action}</span></div></article>)}
   <div className="carousel-controls"><button onClick={()=>setSlide((slide+signals.length-1)%signals.length)} aria-label="Señal anterior">←</button><div>{signals.map((_,i)=><button key={i} className={i===slide?"active":""} onClick={()=>setSlide(i)} aria-label={`Ver señal ${i+1}`}/>)}</div><button onClick={()=>setSlide((slide+1)%signals.length)} aria-label="Siguiente señal">→</button></div>
  </div></section>

  <section className="habits" id="habitos"><div className="habits-head"><p className="material-tag">RECURSO 4 DE 4 · INFOGRAFÍA DIGITAL</p><p className="kicker">5 hábitos para proteger tu información</p><h2>Un mensaje falso puede robarte una cuenta, tus datos o tu dinero.</h2></div><div className="habit-list">{habits.map(({icon:Icon,title,text},i)=><article key={title}><span>{i+1}</span><Icon/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
  <section className="reaction"><div className="reaction-title"><p className="kicker">¿Ya abriste el enlace o compartiste información?</p><h2>Actúa de inmediato.</h2><p>Reaccionar rápido también forma parte de protegerte.</p></div><ol><li><span>1</span><div><b>Cambia tus contraseñas</b><p>Empieza por el correo y las cuentas financieras.</p></div></li><li><span>2</span><div><b>Contacta a la institución</b><p>Usa únicamente su aplicación, sitio o teléfono oficial.</p></div></li><li><span>3</span><div><b>Revisa movimientos y sesiones</b><p>Cierra accesos desconocidos y reporta cualquier cargo.</p></div></li><li><span>4</span><div><b>Avisa a tus contactos</b><p>Hazlo si pudieron suplantar tu identidad o tomar tu cuenta.</p></div></li></ol></section>
  <section className="closing"><ShieldCheck/><div><p>Antes de compartir, abrir o responder:</p><h2>Detente. Verifica. Protege.</h2></div><a href="#quiz" onClick={restart}>Repetir el reto <ArrowRight size={19}/></a></section>
  <footer><div className="brand"><span className="brand-mark"><LockKeyhole size={18}/></span><span>Protege tu <b>vida digital</b></span></div><p>Campaña de sensibilización sobre ciberseguridad · Tu información vale. Protege tu vida digital.</p></footer>
 </main>
}
