import {useState} from "react";
import {AlertTriangle,ArrowRight,Check,ChevronRight,Eye,KeyRound,LockKeyhole,MessageCircleWarning,RotateCcw,ShieldCheck,Smartphone,UserRoundX,X} from "lucide-react";

const questions=[
 {category:"pigeon",channel:"Mensaje",from:"Aviso de cuenta",text:"Su cuenta será suspendida. Abra el siguiente enlace para seguir disfrutando de nuestro contenido.",prompt:"¿Qué haces?",options:["Abro el enlace para evitar que suspendan mi cuenta.","Reviso quién envió el mensaje y después decido si abrirlo.","No abro el enlace; ingreso directamente a la aplicación o página oficial para revisar mi cuenta."],scores:[2,1,0],correct:2,why:"La amenaza de suspensión busca que actúes con prisa. Revisa tu cuenta únicamente desde la aplicación o página oficial."},
 {category:"pigeon",channel:"WhatsApp o audio",from:"Número desconocido",text:"Hola, hijo/a. Me prestaron este celular. ¿Me puedes hacer una transferencia, por favor? Es urgente.",prompt:"¿Qué haces?",options:["Lo llamo a su número conocido o contacto a otro familiar para verificar la situación.","Realizo la transferencia porque reconozco su voz.","Le hago algunas preguntas por mensaje para confirmar su identidad."],scores:[0,2,1],correct:0,why:"Una voz también puede ser imitada. Verifica la solicitud llamando a un número conocido o consultando con otro familiar."},
 {category:"raccoon",channel:"Contraseña",from:"Nueva cuenta",text:"Debes crear una contraseña nueva.",prompt:"¿Cuál elegirías?",options:["MiPerrito34","J!7p%H@2k&Z","12345678"],scores:[1,0,2],correct:1,why:"Una contraseña larga, impredecible y diferente para cada cuenta reduce el riesgo de que alguien la adivine o reutilice."},
 {category:"hedgehog",channel:"Ventana emergente",from:"Alerta del navegador",text:"¡Tu teléfono tiene 13 virus! Haz clic para desinfectar.",prompt:"¿Cuál es tu reacción?",options:["Le doy clic al botón «Limpiar ahora» por si acaso.","Cierro la pestaña o navegador sin tocar nada del mensaje y, si tengo dudas, reviso mi dispositivo mediante herramientas confiables.","Cierro el mensaje, pero me quedo con la duda de si realmente tengo virus."],scores:[2,0,1],correct:1,why:"Las alertas alarmistas del navegador suelen ser engaños. Cierra la pestaña y revisa tu dispositivo únicamente con herramientas confiables."},
 {category:"dog",channel:"Seguridad de cuenta",from:"Configuración",text:"¿Tienes activada la verificación en dos pasos (2FA/MFA) en tus cuentas importantes?",prompt:"Elige la opción que más se parezca a tu situación.",options:["Sí, la tengo activada en mis cuentas importantes.","No, prefiero entrar solamente con mi contraseña o no sé qué es.","La tengo activada solo en algunas cuentas."],scores:[0,2,1],correct:0,why:"La verificación en dos pasos añade una barrera que protege tu cuenta incluso si alguien consigue tu contraseña."},
 {category:"sloth",channel:"Actualización",from:"Sistema operativo",text:"Tu computadora o celular te notifica que hay una actualización del sistema disponible.",prompt:"¿Qué sueles hacer?",options:["La dejo para después y actualizo cuando tengo tiempo.","Actualizo pronto o la programo para un momento conveniente.","Pospongo la actualización durante semanas o meses."],scores:[1,0,2],correct:1,why:"Las actualizaciones corrigen fallas de seguridad. Instálalas pronto o prográmalas para un momento conveniente."},
 {category:"owl",channel:"Aplicación",from:"Filtros divertidos",text:"Una aplicación de filtros solicita acceso a tus contactos, galería, micrófono y ubicación.",prompt:"¿Qué haces?",options:["Acepto todos los permisos para poder utilizarla.","Acepto los permisos y pienso revisarlos después.","Reviso para qué necesita cada permiso y autorizo únicamente los indispensables."],scores:[2,1,0],correct:2,why:"Cada permiso abre acceso a información personal. Autoriza únicamente lo indispensable para la función que utilizarás."},
 {category:"raccoon",channel:"WhatsApp",from:"Uno de tus contactos",text:"Te envié por error un código de seis dígitos. ¿Me lo puedes mandar?",prompt:"¿Qué haces?",options:["No comparto el código y contacto a la persona por otro medio para avisarle que su cuenta podría haber sido robada.","Se lo envío porque el mensaje viene de uno de mis contactos.","Le pregunto para qué necesita el código antes de decidir."],scores:[0,2,1],correct:0,why:"Ese código puede permitir que otra persona registre tu cuenta en otro dispositivo. Nunca lo compartas."},
 {category:"turtle",channel:"Conexión",from:"Wi-Fi pública",text:"Estás en una cafetería o aeropuerto y te conectas a una Wi-Fi pública.",prompt:"¿Qué haces?",options:["Navego, pero evito ingresar a cuentas sensibles.","Navego normalmente, entro a mi banco y hago compras en línea.","Para actividades sensibles prefiero utilizar mis datos móviles o una conexión de confianza."],scores:[1,2,0],correct:2,why:"Las redes públicas pueden exponer tu actividad. Para operaciones sensibles utiliza datos móviles o una conexión de confianza."},
 {category:"pigeon",channel:"Llamada",from:"Supuesto soporte técnico",text:"Alguien dice ser de soporte de Microsoft o Google, asegura que tu cuenta fue hackeada y te pide instalar un programa para controlar tu computadora.",prompt:"¿Qué haces?",options:["Cuelgo, investigo la situación y contacto al soporte desde su página oficial.","Busco rápidamente el nombre del programa antes de instalarlo.","Instalo el programa y sigo sus instrucciones."],scores:[0,1,2],correct:0,why:"El control remoto puede dar acceso a tus datos y cuentas. Cuelga y contacta al soporte únicamente desde su página oficial."},
 {category:"hedgehog",channel:"Notificación",from:"Inicio de sesión",text:"Te llega una notificación de inicio de sesión que no reconoces.",prompt:"¿Qué haces?",options:["Reviso la cuenta cuando tenga tiempo.","Reviso inmediatamente la actividad, cambio la contraseña si es necesario, cierro sesiones desconocidas y refuerzo la seguridad de la cuenta.","La ignoro; quizá fue un error."],scores:[1,0,2],correct:1,why:"Un acceso desconocido requiere atención inmediata para recuperar el control y cerrar la puerta al intruso."},
 {category:"axolotl",channel:"Respaldo",from:"Archivos importantes",text:"¿Qué haces con tus fotos, documentos importantes y recuerdos digitales ante la pérdida o daño de tu dispositivo?",prompt:"Elige la opción que más se parezca a tu situación.",options:["No tengo copias de seguridad. Si pierdo el dispositivo, pierdo los archivos.","Utilizo respaldos automáticos o realizo copias periódicas.","Hago copias de seguridad ocasionalmente."],scores:[2,0,1],correct:1,why:"Los respaldos automáticos o periódicos permiten recuperar tus archivos si el dispositivo se pierde, se daña o es atacado."}
];

const signals=[
 {number:"01",icon:AlertTriangle,title:"Robo de una cuenta mediante un enlace falso",attack:"Envía un mensaje que amenaza con suspender tu cuenta y coloca un enlace que imita la página oficial.",consequence:"Puede robar tu usuario y contraseña, entrar a tu cuenta y cambiar los datos de recuperación para dejarte sin acceso.",action:"No abras el enlace. Entra directamente a la aplicación o página oficial."},
 {number:"02",icon:MessageCircleWarning,title:"Suplantación de un familiar para robar dinero",attack:"Escribe desde otro número, crea una historia urgente e incluso puede imitar la voz de alguien cercano.",consequence:"Puedes transferir dinero al delincuente y compartir datos que después utilizará para engañarte nuevamente.",action:"Llama al número que ya conoces o verifica la situación con otro familiar."},
 {number:"03",icon:KeyRound,title:"Acceso a varias cuentas por una contraseña débil",attack:"Prueba contraseñas comunes, datos relacionados contigo o claves filtradas en otros servicios.",consequence:"Puede entrar a tu correo, redes sociales o tiendas y utilizar esas cuentas para robar información o suplantar tu identidad.",action:"Crea contraseñas largas, impredecibles y diferentes para cada cuenta."},
 {number:"04",icon:Eye,title:"Robo y uso indebido de tus datos personales",attack:"Promete un premio o beneficio y solicita tu nombre, dirección, teléfono o información bancaria.",consequence:"Tus datos pueden utilizarse para cometer fraudes, abrir cuentas a tu nombre, enviarte engaños más creíbles o intentar robar tu identidad.",action:"No compartas información. Confirma la promoción en los canales oficiales."},
 {number:"05",icon:LockKeyhole,title:"Robo de dinero mediante una llamada falsa",attack:"Se hace pasar por personal del banco, te alarma con un supuesto problema y pide el código que llegó a tu celular.",consequence:"Con ese código puede autorizar operaciones, entrar a tu banca digital o realizar movimientos sin tu permiso.",action:"No compartas el código. Cuelga y llama al número oficial del banco."},
 {number:"06",icon:Smartphone,title:"Uso indebido de información por una aplicación",attack:"Ofrece una función atractiva, pero solicita acceso innecesario a contactos, fotos, micrófono y ubicación.",consequence:"La aplicación podría recopilar, compartir o utilizar tu información y la de tus contactos sin que seas plenamente consciente.",action:"Revisa cada permiso y autoriza únicamente los indispensables."},
 {number:"07",icon:MessageCircleWarning,title:"Robo de WhatsApp y suplantación de identidad",attack:"Desde la cuenta de un contacto pide el código de seis dígitos que llegó a tu celular y dice que fue enviado por error.",consequence:"Puede apoderarse de tu WhatsApp, leer conversaciones y hacerse pasar por ti para pedir dinero o información a tus contactos.",action:"Nunca compartas el código y avisa a tu contacto por otro medio."},
 {number:"08",icon:ShieldCheck,title:"Ingreso a tu cuenta después de robar la contraseña",attack:"Consigue tu clave mediante una filtración, un engaño o una página falsa e intenta utilizarla inmediatamente.",consequence:"Si no existe una segunda barrera, puede entrar, consultar información privada y tomar el control de la cuenta.",action:"Activa la verificación en dos pasos en tus cuentas importantes."},
 {number:"09",icon:UserRoundX,title:"Control remoto y robo desde tu dispositivo",attack:"Se presenta como técnico y te convence de instalar una aplicación que le permite manejar tu teléfono a distancia.",consequence:"Puede ver contraseñas y códigos, abrir aplicaciones bancarias, copiar archivos o realizar operaciones mientras observa tu pantalla.",action:"No instales nada. Comunícate directamente con el soporte oficial."},
 {number:"10",icon:AlertTriangle,title:"Toma de control de una cuenta",attack:"Entra con credenciales robadas y espera que ignores o retrases la alerta de inicio de sesión.",consequence:"Puede cambiar tu contraseña, cerrar tus sesiones, acceder a información privada y usar tu cuenta para defraudar a otras personas.",action:"Cambia tu contraseña, cierra las sesiones abiertas y activa la verificación en dos pasos."}
];

const habits=[
 {icon:KeyRound,title:"Contraseñas diferentes",text:"Usa una clave única y difícil de adivinar para cada cuenta importante."},
 {icon:ShieldCheck,title:"Verificación en dos pasos",text:"Actívala y nunca compartas los códigos que recibas."},
 {icon:Eye,title:"Pausa antes de abrir",text:"Revisa remitente, dirección, enlaces y archivos antes de tocarlos."},
 {icon:UserRoundX,title:"Datos bajo control",text:"Evita publicar ubicación, documentos, teléfonos o información financiera."},
 {icon:Smartphone,title:"Equipos actualizados",text:"Instala actualizaciones de aplicaciones y del sistema operativo."}
];

export default function Home(){
 const[started,setStarted]=useState(false),[current,setCurrent]=useState(0),[selected,setSelected]=useState<number|null>(null),[answers,setAnswers]=useState<number[]>([]),[done,setDone]=useState(false),[slide,setSlide]=useState(0);
 const q=questions[current];
 function choose(i:number){if(selected!==null)return;setSelected(i);setAnswers(previous=>{const updated=[...previous];updated[current]=q.scores[i];return updated})}
 function next(){if(current===questions.length-1)setDone(true);else{setCurrent(n=>n+1);setSelected(null)}}
 function restart(){setCurrent(0);setAnswers([]);setSelected(null);setDone(false);setStarted(true)}
 const answerAt=(index:number)=>answers[index]??1;
 const safetyAt=(index:number)=>(2-answerAt(index))/2;
 const riskAt=(index:number)=>answerAt(index)/2;
 const average=(values:number[])=>values.reduce((sum,value)=>sum+value,0)/values.length;
 const safeRate=answers.filter(value=>value===0).length/questions.length;
 const pauseRate=answers.filter(value=>value===1).length/questions.length;
 const riskRate=answers.filter(value=>value===2).length/questions.length;
 const profileAffinities=[
  {category:"pigeon",score:60*average([riskAt(0),riskAt(1),riskAt(9)])+40*riskRate},
  {category:"raccoon",score:55*average([riskAt(2),riskAt(7)])+30*pauseRate+15*(1-Math.abs(riskRate-safeRate))},
  {category:"hedgehog",score:55*average([safetyAt(3),safetyAt(10)])+25*safeRate+20*pauseRate},
  {category:"dog",score:55*average([safetyAt(1),safetyAt(4),safetyAt(7),safetyAt(10)])+30*safeRate+15*pauseRate},
  {category:"turtle",score:45*safetyAt(8)+35*pauseRate+20*safeRate},
  {category:"sloth",score:55*average([riskAt(5),riskAt(10),riskAt(11)])+30*pauseRate+15*riskRate},
  {category:"owl",score:50*safeRate+40*average([safetyAt(0),safetyAt(3),safetyAt(6),safetyAt(9),safetyAt(10)])+10*pauseRate},
  {category:"axolotl",score:55*safetyAt(11)+30*safeRate+15*pauseRate}
 ];
 const winningProfile=[...profileAffinities].sort((a,b)=>b.score-a.score)[0];
 const animalResults={
  pigeon:{sprite:"one",name:"Paloma de phishing",title:"Eres una Paloma de phishing",trait:"Curiosa, confiada y rápida para responder",strength:"Tu fortaleza es la disposición para comunicarte, ayudar y resolver las situaciones con rapidez.",opportunity:"La urgencia o una historia convincente pueden adelantarse a tu verificación.",recommendation:"Haz una pausa antes de abrir enlaces, transferir dinero o instalar programas; confirma siempre la solicitud por un canal oficial."},
  raccoon:{sprite:"one",name:"Mapache de contraseñas",title:"Eres un Mapache de contraseñas",trait:"Práctico, ingenioso y apegado a sus hábitos",strength:"Tu fortaleza es encontrar soluciones sencillas para organizar y recordar tus accesos digitales.",opportunity:"La comodidad puede llevarte a usar claves predecibles, repetirlas o tratar un código como si no fuera secreto.",recommendation:"Utiliza un gestor de contraseñas, crea una clave diferente para cada cuenta y nunca compartas códigos de verificación."},
  hedgehog:{sprite:"one",name:"Erizo de alertas",title:"Eres un Erizo de alertas",trait:"Atento y preparado para levantar sus defensas",strength:"Tu fortaleza es percibir cuando algo parece fuera de lugar y reaccionar ante posibles señales de peligro.",opportunity:"Una alerta alarmista puede hacerte actuar por miedo o, por el contrario, dejarte paralizado por la duda.",recommendation:"No pulses avisos inesperados; revisa el problema desde herramientas confiables y atiende de inmediato los accesos que no reconozcas."},
  dog:{sprite:"one",name:"Perro de MFA",title:"Eres un Perro de MFA",trait:"Leal, protector y cuidadoso con los suyos",strength:"Tu fortaleza es proteger lo importante y buscar una confirmación antes de confiar por completo.",opportunity:"Esa protección pierde fuerza cuando una cuenta depende únicamente de su contraseña.",recommendation:"Activa la verificación en dos pasos en tu correo, redes sociales, banca y todas tus cuentas importantes."},
  turtle:{sprite:"two",name:"Tortuga de red segura",title:"Eres una Tortuga de red segura",trait:"Prudente, serena y consciente de su entorno",strength:"Tu fortaleza es evitar decisiones precipitadas y buscar espacios digitales donde te sientas protegido.",opportunity:"La calma puede convertirse en exceso de confianza cuando navegas fuera de una conexión segura.",recommendation:"Para compras, banca o información privada, utiliza datos móviles o una red de confianza y evita operaciones sensibles en Wi-Fi pública."},
  sloth:{sprite:"two",name:"Perezoso de actualizaciones",title:"Eres un Perezoso de actualizaciones",trait:"Tranquilo y difícil de presionar",strength:"Tu fortaleza es mantener la calma y no dejarte dominar fácilmente por mensajes alarmistas.",opportunity:"Posponer actualizaciones, alertas o respaldos puede mantener abiertas fallas que ya tienen solución.",recommendation:"Activa las actualizaciones automáticas y reserva un momento fijo para revisar alertas, sesiones y copias de seguridad."},
  owl:{sprite:"two",name:"Búho de inteligencia",title:"Eres un Búho de inteligencia",trait:"Observador, analítico y precavido",strength:"Tu fortaleza es comparar señales, revisar detalles y pensar antes de conceder acceso o realizar una acción.",opportunity:"Saber qué hacer no siempre garantiza que todas tus cuentas y dispositivos mantengan la misma protección.",recommendation:"Convierte tu análisis en rutina: revisa permisos, activa 2FA, actualiza tus equipos y verifica periódicamente tus sesiones."},
  axolotl:{sprite:"two",name:"Ajolote de backups",title:"Eres un Ajolote de backups",trait:"Adaptable, previsor y capaz de recuperarse",strength:"Tu fortaleza es pensar en la continuidad y valorar que tu información pueda recuperarse después de un problema.",opportunity:"Un respaldo ocasional o nunca comprobado puede no estar disponible justo cuando lo necesites.",recommendation:"Configura copias automáticas, conserva al menos una copia adicional y prueba periódicamente que tus archivos puedan restaurarse."}
 };
 const result=animalResults[winningProfile.category as keyof typeof animalResults];
 const profileAffinity=Math.min(100,Math.round(winningProfile.score));
 const assetBase="./";
 const selectedScore=selected===null?null:q.scores[selected];
 const feedback=selectedScore===2?"Esta respuesta aumenta tu nivel de riesgo.":selectedScore===1?"Es una precaución útil, pero todavía existe riesgo.":"Esta es la acción más segura.";
 return <main>
  <header className="topbar"><a className="brand" href="#inicio"><span className="brand-mark"><LockKeyhole size={20}/></span><span>Protege tu <b>vida digital</b></span></a><nav aria-label="Navegación principal"><a href="#materiales">Recursos</a><a href="#quiz">Quiz</a><a href="#senales">Detecta estafas</a><a className="nav-quiz" href="#habitos">Protégete</a></nav></header>
  <section className="hero" id="inicio">
   <div className="hero-copy"><p className="material-tag">RECURSO 1 DE 4 · BANNER DIGITAL</p><p className="eyebrow"><span/>Tu información vale. Protégela.</p><h1>¿Eres blanco fácil para los <em>hackers</em>? Averígualo en 12 preguntas</h1><p className="lead">Quiz de 12 preguntas <b>GRATUITO</b> para saber cuál es tu animal de seguridad digital.</p><a className="primary" href="#materiales">Quiz GRATUITO <ArrowRight size={20}/></a><p className="safe-note"><ShieldCheck size={17}/>Detente. Verifica. Protege.</p></div>
   <div className="hero-visual"><img src={`${assetBase}hero-security-animals.webp`} alt="Mensaje bancario sospechoso rodeado por animales de seguridad digital"/></div>
  </section>
  <section className="materials-map" id="materiales" aria-label="Recursos de la campaña"><p>Esta campaña busca que conozcas mejor tu seguridad digital y puedas navegar de una manera más segura.</p><div><a href="#inicio"><span>01</span>Banner</a><a href="#quiz"><span>02</span>¿Qué tan fácil sería engañarte?</a><a href="#senales"><span>03</span>Señales de que estás frente a una estafa digital</a><a href="#habitos"><span>04</span>5 hábitos para proteger tu información</a></div></section>

  <section className="quiz-section" id="quiz"><div className="section-intro"><p className="material-tag light">RECURSO 2 DE 4 · QUIZ DE EVALUACIÓN</p></div>
   <div className="quiz-shell">
   {!started?<div className="quiz-welcome"><div className="big-shield"><ShieldCheck size={58}/></div><div><span className="mini-label">12 SITUACIONES · 8 ANIMALES DE SEGURIDAD</span><h3>Inicia el Quiz Gratis aquí</h3><p>Lee cada situación y elige la respuesta que más se parezca a lo que harías. Responde con sinceridad para obtener un resultado útil.</p><button className="primary" onClick={()=>setStarted(true)}>Iniciar quiz <ChevronRight size={21}/></button></div></div>
   :done?<div className="result"><div className={`animal-portrait sprite-${result.sprite} ${winningProfile.category}`} style={{backgroundImage:`url(${assetBase}animal-results-${result.sprite}.webp)`}} role="img" aria-label={`Ilustración de ${result.name}`}/><p className="mini-label">TU PERFIL DE COMPORTAMIENTO DIGITAL · {profileAffinity}% DE AFINIDAD</p><h3>{result.title}</h3><h4>{result.trait}</h4><div className="profile-insights"><article className="strength"><b>Tu fortaleza</b><p>{result.strength}</p></article><article className="opportunity"><b>Tu área de oportunidad</b><p>{result.opportunity}</p></article><article className="recommendation"><b>Tu siguiente paso</b><p>{result.recommendation}</p></article></div><div className="survey result-survey"><p className="mini-label">TU OPINIÓN TAMBIÉN CUENTA</p><h3>Cuéntanos qué animal de seguridad eres</h3><p>Ahora que conoces tu resultado, ayúdanos dejando un comentario en este breve formulario.</p><iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdVlpiZOhdv8jcaMHseabzMs9kikyS7ddIJCNGBT2aLJzG4Hg/viewform?embedded=true" title="Formulario de comentarios sobre la campaña">Cargando…</iframe></div><button className="secondary" onClick={restart}><RotateCcw size={19}/>Volver a intentarlo</button></div>
   :<div className="question-view"><div className="quiz-progress"><span>Situación {current+1} de {questions.length}</span><div><i style={{width:`${((current+1)/questions.length)*100}%`}}/></div></div><div className="message-card"><div className="message-meta"><span><MessageCircleWarning size={18}/>{q.channel}</span><small>{q.from}</small></div><p>“{q.text}”</p></div><h3>{q.prompt}</h3><div className="answers">{q.options.map((option,i)=><button key={option} className={selected===null?"":i===q.correct?"correct":i===selected?"wrong":"muted"} onClick={()=>choose(i)} disabled={selected!==null}><span>{String.fromCharCode(65+i)}</span>{option}{selected!==null&&i===q.correct?<Check size={20}/>:selected===i&&i!==q.correct?<X size={20}/>:null}</button>)}</div>{selected!==null&&<div className={`feedback ${selectedScore===0?"good":"care"}`}><b>{feedback}</b><p>{q.why}</p><small>Esta respuesta suma {selectedScore} {selectedScore===1?"punto":"puntos"} de riesgo.</small><button onClick={next}>{current===questions.length-1?"Ver mi resultado":"Siguiente situación"}<ArrowRight size={18}/></button></div>}</div>}
   </div>
  </section>

  <section className="signals" id="senales"><div className="section-intro left"><p className="material-tag">RECURSO 3 DE 4 · CARRUSEL INFORMATIVO</p><p className="kicker">Situaciones que pueden afectar tu vida digital</p><h2>Señales de que estás frente a una estafa digital</h2><p>Conoce cómo actúan los delincuentes, qué consecuencias puede tener caer en la trampa y cómo protegerte.</p></div><div className="carousel">
   {signals.map(({number,icon:Icon,title,attack,consequence,action},i)=><article key={title} className={i===slide?"active":""} aria-hidden={i!==slide}><div className="slide-count">{number} / 10</div><div className="slide-icon"><Icon/></div><h3>{title}</h3><div className="threat-block"><b>Lo que hace el atacante</b><p>{attack}</p></div><div className="consequence-block"><b>Si caes en la trampa</b><p>{consequence}</p></div><div className="slide-action"><ShieldCheck size={23}/><span><b>Qué hacer:</b> {action}</span></div></article>)}
   <div className="carousel-controls"><button onClick={()=>setSlide((slide+signals.length-1)%signals.length)} aria-label="Señal anterior">←</button><div>{signals.map((_,i)=><button key={i} className={i===slide?"active":""} onClick={()=>setSlide(i)} aria-label={`Ver señal ${i+1}`}/>)}</div><button onClick={()=>setSlide((slide+1)%signals.length)} aria-label="Siguiente señal">→</button></div>
  </div></section>

  <section className="habits" id="habitos"><div className="habits-head"><p className="material-tag">RECURSO 4 DE 4 · INFOGRAFÍA DIGITAL</p><p className="kicker">5 hábitos para proteger tu información</p><h2>Un mensaje falso puede robarte una cuenta, tus datos o tu dinero.</h2></div><div className="habit-list">{habits.map(({icon:Icon,title,text},i)=><article key={title}><span>{i+1}</span><Icon/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
  <section className="reaction"><div className="reaction-title"><p className="kicker">¿Ya abriste el enlace o compartiste información?</p><h2>Actúa de inmediato.</h2><p>Reaccionar rápido también forma parte de protegerte.</p></div><ol><li><span>1</span><div><b>Cambia tus contraseñas</b><p>Empieza por el correo y las cuentas financieras.</p></div></li><li><span>2</span><div><b>Contacta a la institución</b><p>Usa únicamente su aplicación, sitio o teléfono oficial.</p></div></li><li><span>3</span><div><b>Revisa movimientos y sesiones</b><p>Cierra accesos desconocidos y reporta cualquier cargo.</p></div></li><li><span>4</span><div><b>Avisa a tus contactos</b><p>Hazlo si pudieron suplantar tu identidad o tomar tu cuenta.</p></div></li></ol></section>
  <section className="closing"><ShieldCheck/><div><p>Antes de compartir, abrir o responder:</p><h2>Detente. Verifica. Protege.</h2></div><a href="#quiz" onClick={restart}>Repetir el reto <ArrowRight size={19}/></a></section>
  <footer><div className="brand"><span className="brand-mark"><LockKeyhole size={18}/></span><span>Protege tu <b>vida digital</b></span></div><p>Campaña de sensibilización sobre ciberseguridad · Tu información vale. Protege tu vida digital.</p></footer>
 </main>
}
