import {useState} from "react";
import {AlertTriangle,ArrowRight,ChevronRight,Copy,Eye,KeyRound,LockKeyhole,MessageCircleWarning,RotateCcw,Share2,ShieldCheck,Smartphone,UserRoundX} from "lucide-react";

type Profile="pigeon"|"raccoon"|"hedgehog"|"dog"|"sloth"|"owl"|"turtle"|"axolotl";
type Affinity=Partial<Record<Profile,number>>;
type Question={channel:string;from:string;text:string;prompt:string;options:string[];affinities:Affinity[]};

const questions:Question[]=[
 {channel:"Mensaje",from:"Aviso de cuenta",text:"Su cuenta será suspendida. Verifique sus datos en el siguiente enlace para conservar el acceso.",prompt:"¿Qué se parece más a lo que harías?",options:["Reviso el remitente y el enlace; si ambos parecen legítimos, continúo desde el mensaje.","Entro por mi cuenta a la aplicación o página oficial para comprobar si realmente existe algún problema.","Busco en Internet si otras personas han recibido el mismo mensaje antes de decidir qué hacer."],affinities:[{owl:3,pigeon:1},{hedgehog:3,owl:1},{owl:3,pigeon:1}]},
 {channel:"Audio",from:"Número desconocido",text:"Me prestaron este celular. Necesito que me hagas una transferencia, por favor. Es urgente.",prompt:"¿Qué harías primero?",options:["Le hago algunas preguntas que solo esa persona debería saber antes de continuar.","Intento comunicarme con esa persona mediante su número habitual o con alguien cercano a ella.","Si reconozco claramente su voz y la situación parece creíble, atiendo la petición y después confirmo qué ocurrió."],affinities:[{pigeon:3,owl:1},{hedgehog:3,pigeon:1},{pigeon:3}]},
 {channel:"Contraseña",from:"Nueva cuenta",text:"Una página te pide crear una contraseña que nunca hayas utilizado.",prompt:"¿Cuál estrategia se parece más a la tuya?",options:["Creo una contraseña larga a partir de varias palabras o una frase que pueda recordar y que no utilice en otras cuentas.","Utilizo una palabra que recuerde fácilmente, pero cambio letras por números y símbolos.","Dejo que un gestor de contraseñas genere y guarde una contraseña aleatoria para esa cuenta."],affinities:[{raccoon:3,owl:1},{raccoon:3},{raccoon:3,dog:1}]},
 {channel:"Ventana emergente",from:"Alerta del navegador",text:"¡Detectamos amenazas en tu dispositivo! Se recomienda realizar una limpieza.",prompt:"¿Qué harías?",options:["Cierro el aviso y después reviso el estado del dispositivo desde sus propias herramientas de seguridad.","Investigo el nombre del aviso o de la herramienta que aparece antes de decidir si hacer algo.","Si el aviso parece provenir de una empresa conocida, sigo las indicaciones que muestra."],affinities:[{hedgehog:3,owl:1},{owl:3,hedgehog:1},{pigeon:3}]},
 {channel:"Seguridad de cuentas",from:"Correo, mensajería y redes",text:"Piensa en tu correo, WhatsApp, redes sociales y otras cuentas importantes.",prompt:"¿Cuál situación describe mejor cómo las proteges?",options:["Tengo activada una segunda forma de verificación en las cuentas que considero más importantes.","Prefiero concentrarme en utilizar contraseñas diferentes y difíciles de adivinar.","Siempre que una cuenta lo permite, activo una segunda forma de verificación además de la contraseña."],affinities:[{dog:3,raccoon:1},{raccoon:3,dog:1},{dog:3,raccoon:1}]},
 {channel:"Actualización",from:"Sistema operativo",text:"Estás utilizando tu computadora y aparece una actualización que requiere reiniciarla. Justo estás ocupado.",prompt:"¿Qué haces normalmente?",options:["Termino lo que estoy haciendo y la dejo programada para más tarde ese mismo día o para un momento cercano.","La pospongo hasta que tenga un momento en el que pueda revisar tranquilamente qué cambios incluye.","Suelo esperar algunos días; si el dispositivo continúa funcionando correctamente, no veo necesidad de apresurarme."],affinities:[{dog:3,sloth:1},{sloth:3,owl:1},{sloth:3}]},
 {channel:"Aplicación",from:"Editor de fotografías",text:"Al abrirla solicita acceso a cámara, micrófono, ubicación, contactos y galería.",prompt:"¿Qué se parece más a lo que harías?",options:["Reviso los permisos uno por uno y habilito únicamente los que entiendo que necesita para las funciones que voy a utilizar.","Acepto inicialmente los permisos para probar la aplicación y, si decido conservarla, después reviso su configuración.","Antes de aceptar, reviso para qué utiliza los datos y decido si realmente quiero instalarla."],affinities:[{owl:3,dog:1},{sloth:3},{owl:3,hedgehog:1}]},
 {channel:"Mensaje",from:"Cuenta habitual de un amigo",text:"Te debió llegar un código de seis dígitos. Lo puse por error con tu número. ¿Me lo pasas?",prompt:"¿Qué harías?",options:["Primero le pregunto qué estaba intentando hacer y por qué necesita exactamente ese código.","No envío el código y trato de comunicarme con esa persona de otra manera para confirmar que realmente es ella.","Si la conversación y la forma de escribir coinciden con esa persona, considero enviárselo."],affinities:[{raccoon:3,pigeon:1},{raccoon:3,hedgehog:1},{pigeon:3}]},
 {channel:"Conexión",from:"Wi-Fi de una cafetería",text:"Necesitas conectarte a Internet y hay una red gratuita del establecimiento.",prompt:"¿Cuál opción se parece más a tu comportamiento?",options:["Me conecto, pero dejo las operaciones importantes para cuando tenga una conexión que controle mejor.","Si necesito entrar a una cuenta importante, prefiero cambiar a mis datos móviles.","Si confirmo con el personal cuál es la red oficial, la utilizo normalmente para mis actividades."],affinities:[{turtle:3,owl:1},{turtle:3,dog:1},{turtle:3,pigeon:1}]},
 {channel:"Llamada",from:"Supuesto soporte técnico",text:"Conoce tu nombre y correo, afirma que detectaron actividad sospechosa en tu cuenta y ofrece guiarte para solucionarlo.",prompt:"¿Qué harías?",options:["Escucho las instrucciones, pero antes de instalar algo o proporcionar información investigo los datos que me dieron.","Termino la llamada y contacto por mi cuenta a la empresa mediante sus canales oficiales.","Si puede demostrar que conoce información real sobre mi cuenta, continúo la llamada con precaución."],affinities:[{owl:3,pigeon:1},{hedgehog:3,dog:1},{pigeon:3}]},
 {channel:"Notificación",from:"Inicio de sesión",text:"Recibes una notificación de un inicio de sesión desde un dispositivo que no reconoces.",prompt:"¿Qué se parece más a tu reacción?",options:["Entro inmediatamente a la cuenta para revisar sesiones, dispositivos y opciones de seguridad.","Primero pienso si pude haber iniciado sesión recientemente desde otro dispositivo; si no lo recuerdo, reviso la cuenta.","Observo si aparecen más alertas antes de hacer cambios, porque algunas notificaciones pueden generarse por error."],affinities:[{hedgehog:3,dog:1},{owl:3,hedgehog:1},{sloth:3}]},
 {channel:"Respaldo",from:"Fotografías y documentos",text:"Si mañana perdieras uno de tus dispositivos, ¿qué ocurriría?",prompt:"Elige la opción que más se parezca a tu situación.",options:["Recuperaría la mayoría porque suelo guardar manualmente lo más importante en otro lugar.","Probablemente perdería algunas cosas, aunque las más importantes suelen estar en aplicaciones o servicios en línea.","Podría recuperar prácticamente todo porque utilizo algún sistema de respaldo periódico o automático."],affinities:[{axolotl:3,dog:1},{axolotl:3},{axolotl:3,dog:1}]}
];

const profiles:Profile[]=["owl","hedgehog","dog","turtle","axolotl","raccoon","pigeon","sloth"];
const patternMatches:Record<Profile,number[][]>={
 pigeon:[[0,0],[0,2],[1,0],[1,2],[3,2],[7,0],[7,2],[9,0],[9,2]],
 raccoon:[[2,0],[2,1],[2,2],[4,1],[7,0],[7,1]],
 hedgehog:[[0,1],[1,1],[3,0],[6,2],[7,1],[9,1],[10,0]],
 dog:[[2,2],[4,0],[4,2],[5,0],[8,1],[9,1],[10,0],[11,0],[11,2]],
 sloth:[[5,1],[5,2],[6,1],[10,1],[10,2]],
 owl:[[0,0],[0,2],[1,0],[2,0],[3,1],[5,1],[6,0],[6,2],[9,0],[10,1]],
 turtle:[[0,1],[1,1],[4,2],[7,1],[8,0],[8,1],[9,1]],
 axolotl:[[4,2],[5,0],[10,0],[11,0],[11,2]]
};

const signals=[
 {number:"01",icon:AlertTriangle,title:"Robo de una cuenta mediante un enlace falso",attack:"Envía un mensaje que amenaza con suspender tu cuenta y coloca un enlace que imita la página oficial.",consequence:"Puede robar tu usuario y contraseña, entrar a tu cuenta y cambiar los datos de recuperación para dejarte sin acceso.",action:"No abras el enlace. Entra directamente a la aplicación o página oficial."},
 {number:"02",icon:MessageCircleWarning,title:"Suplantación de un familiar para robar dinero",attack:"Escribe desde otro número, crea una historia urgente e incluso puede imitar la voz de alguien cercano.",consequence:"Puedes transferir dinero al delincuente y compartir datos que después utilizará para engañarte nuevamente.",action:"Llama al número que ya conoces o verifica la situación con otro familiar."},
 {number:"03",icon:KeyRound,title:"Acceso a varias cuentas por una contraseña débil",attack:"Prueba contraseñas comunes, datos relacionados contigo o claves filtradas en otros servicios.",consequence:"Puede entrar a tu correo, redes sociales o tiendas y utilizar esas cuentas para robar información o suplantar tu identidad.",action:"Crea contraseñas largas, impredecibles y diferentes para cada cuenta."},
 {number:"04",icon:Eye,title:"Robo y uso indebido de tus datos personales",attack:"Promete un premio o beneficio y solicita tu nombre, dirección, teléfono o información bancaria.",consequence:"Tus datos pueden utilizarse para cometer fraudes, abrir cuentas a tu nombre, enviarte engaños más creíbles o intentar robar tu identidad.",action:"No compartas información. Confirma la promoción en los canales oficiales."},
 {number:"05",icon:LockKeyhole,title:"Robo de dinero mediante una llamada falsa",attack:"Se hace pasar por personal del banco, te alarma con un supuesto problema y pide el código que llegó a tu celular.",consequence:"Con ese código puede autorizar operaciones, entrar a tu banca digital o realizar movimientos sin tu permiso.",action:"No compartas el código. Cuelga y llama al número oficial del banco."},
 {number:"06",icon:Smartphone,title:"Uso indebido de información por una aplicación",attack:"Ofrece una función atractiva, pero solicita acceso innecesario a contactos, fotos, micrófono y ubicación.",consequence:"La aplicación podría recopilar, compartir o utilizar tu información y la de tus contactos sin que seas plenamente consciente.",action:"Revisa cada permiso y autoriza únicamente los indispensables."},
 {number:"07",icon:MessageCircleWarning,title:"Robo de WhatsApp y suplantación de identidad",attack:"Desde la cuenta de un contacto pide el código de seis dígitos que llegó a tu celular y dice que fue enviado por error.",consequence:"Puede apoderarse de tu WhatsApp, leer conversaciones y hacerse pasar por ti para pedir dinero o información a tus contactos.",action:"Nunca compartas el código y avisa a tu contacto por otro medio."},
 {number:"08",icon:ShieldCheck,title:"Ingreso a tu cuenta después de robar la contraseña",attack:"Consigue tu clave mediante una filtración, un engaño o una página falsa e intenta utilizarla inmediatamente.",consequence:"Si no existe una segunda barrera, puede entrar, consultar información privada y tomar el control de la cuenta.",action:"Activa la verificación en dos pasos en tus cuentas importantes."},
 {number:"09",icon:UserRoundX,title:"Control remoto y robo desde tu dispositivo",attack:"Se presenta como técnico y te convence de instalar una aplicación que le permite manejar tu teléfono a distancia.",consequence:"Puede ver contraseñas y códigos, abrir aplicaciones bancarias, copiar archivos o realizar operaciones mientras observa tu pantalla.",action:"No instales nada. Comunícate directamente con el soporte oficial."},
 {number:"10",icon:AlertTriangle,title:"Toma de control de una cuenta",attack:"Entra con credenciales robadas y espera que ignores o retrases la alerta de inicio de sesión.",consequence:"Puede cambiar tu contraseña, cerrar tus sesiones, acceder a información privada y usar tu cuenta para defraudar a otras personas.",action:"Cambia tu contraseña, cierra las sesiones abiertas y activa la verificación en dos pasos."}
];

const habits=[
 {icon:KeyRound,title:"Contraseñas diferentes",text:"Usa una clave única y difícil de adivinar para cada cuenta importante."},
 {icon:ShieldCheck,title:"Verificación en dos pasos",text:"Actívala y nunca compartas los códigos que recibas."},
 {icon:Eye,title:"Pausa antes de abrir",text:"Revisa remitente, dirección, enlaces y archivos antes de tocarlos."},
 {icon:UserRoundX,title:"Datos bajo control",text:"Evita publicar ubicación, documentos, teléfonos o información financiera."},
 {icon:Smartphone,title:"Equipos actualizados",text:"Instala actualizaciones de aplicaciones y del sistema operativo."}
];

export default function Home(){
 const[started,setStarted]=useState(false),[current,setCurrent]=useState(0),[selected,setSelected]=useState<number|null>(null),[answers,setAnswers]=useState<number[]>([]),[done,setDone]=useState(false),[slide,setSlide]=useState(0),[copied,setCopied]=useState(false);
 const q=questions[current];
 function choose(i:number){if(selected!==null)return;setSelected(i);setAnswers(previous=>{const updated=[...previous];updated[current]=i;return updated})}
 function next(){if(current===questions.length-1)setDone(true);else{setCurrent(n=>n+1);setSelected(null)}}
 function restart(){setCurrent(0);setAnswers([]);setSelected(null);setDone(false);setCopied(false);setStarted(true)}
 const profileAffinities=profiles.map((category,priority)=>{
  const patternQuestions=[...new Set(patternMatches[category].map(([question])=>question))];
  const patternHits=patternQuestions.filter(question=>patternMatches[category].some(([qIndex,option])=>qIndex===question&&answers[qIndex]===option)).length;
  const compatibility=patternHits/patternQuestions.length*100;
  let direct=0,maximum=0;
  questions.forEach((question,index)=>{
   const values=question.affinities.map(option=>option[category]??0);
   const baseline=Math.min(...values);
   direct+=(values[answers[index]]??baseline)-baseline;
   maximum+=Math.max(...values)-baseline;
  });
  // Una afinidad presente en las tres opciones no distingue conductas; se apoya en el patrón completo.
  const directNormalized=maximum?direct/maximum*100:compatibility;
  const primaryHits=answers.filter((answer,question)=>(questions[question]?.affinities[answer]?.[category]??0)===3).length;
  const directSupport=answers.filter((answer,question)=>(questions[question]?.affinities[answer]?.[category]??0)>0).length;
  const supportedQuestions=new Set<number>();
  answers.forEach((answer,question)=>{
   if((questions[question]?.affinities[answer]?.[category]??0)>0)supportedQuestions.add(question);
   if(patternMatches[category].some(([qIndex,option])=>qIndex===question&&option===answer))supportedQuestions.add(question);
  });
  // Evita que un único hábito aislado determine por sí solo Tortuga, Ajolote o cualquier otro perfil.
  const coherence=supportedQuestions.size>=3?1:supportedQuestions.size===2?.9:.72;
  return{category,score:(directNormalized*.70+compatibility*.30)*coherence,primaryHits,directSupport,compatibility,priority};
 });
 // Desempate determinista: afinidad final, coincidencias +3, preguntas de apoyo, patrón y prioridad fija.
 const winningProfile=[...profileAffinities].sort((a,b)=>b.score-a.score||b.primaryHits-a.primaryHits||b.directSupport-a.directSupport||b.compatibility-a.compatibility||a.priority-b.priority)[0];
 const animalResults={
  pigeon:{sprite:"one",name:"Paloma",title:"Eres una Paloma",trait:"El Confiado",strength:"Tus respuestas muestran que te comunicas con naturalidad y sabes desenvolverte con facilidad en entornos digitales.",opportunity:"La familiaridad, la urgencia o una apariencia legítima pueden sustituir una verificación más sólida.",recommendation:"Confirma las solicitudes por un canal oficial antes de abrir enlaces, compartir información o enviar dinero."},
  raccoon:{sprite:"one",name:"Mapache",title:"Eres un Mapache",trait:"El Práctico",strength:"Tienes facilidad para administrar tus cuentas y encontrar soluciones prácticas para tus accesos digitales.",opportunity:"La comodidad puede llevarte a repetir contraseñas o tratar un código de acceso como si no fuera secreto.",recommendation:"Utiliza un gestor de contraseñas y conserva una clave única para cada cuenta."},
  hedgehog:{sprite:"one",name:"Erizo",title:"Eres un Erizo",trait:"El Reactivo",strength:"Detectas señales de peligro y tiendes a actuar cuando percibes que algo no está bien.",opportunity:"Una reacción rápida funciona mejor cuando también está verificada y se realiza desde canales confiables.",recommendation:"Ante una alerta, entra directamente a la cuenta o herramienta oficial y revisa allí lo ocurrido."},
  dog:{sprite:"one",name:"Perro",title:"Eres un Perro",trait:"El Guardián",strength:"Proteges activamente tus cuentas y prefieres colocar barreras antes de que ocurra un problema.",opportunity:"Ninguna barrera es infalible; conviene complementar la prevención con análisis y recuperación.",recommendation:"Combina la verificación en dos pasos con respaldos y revisiones periódicas de tus sesiones."},
  turtle:{sprite:"two",name:"Tortuga",title:"Eres una Tortuga",trait:"El Cauteloso",strength:"Sabes reducir tu exposición y protegerte incluso cuando estás fuera de tu entorno habitual.",opportunity:"Evitar riesgos ayuda, pero no sustituye otras barreras de seguridad para tus cuentas y datos.",recommendation:"Mantén tu prudencia y acompáñala con 2FA, contraseñas únicas y respaldos."},
  sloth:{sprite:"two",name:"Perezoso",title:"Eres un Perezoso",trait:"El Postergador",strength:"Reconoces muchas medidas de seguridad y sueles identificar por qué son importantes.",opportunity:"El conocimiento pierde fuerza cuando las actualizaciones o alertas se dejan para después.",recommendation:"Programa un momento cercano para actualizar y activa automatizaciones siempre que estén disponibles."},
  owl:{sprite:"two",name:"Búho",title:"Eres un Búho",trait:"El Analítico",strength:"Tu pensamiento crítico te ayuda a observar, investigar y cuestionar antes de tomar una decisión.",opportunity:"Analizar demasiado tiempo puede retrasar una acción cuando una amenaza requiere respuesta inmediata.",recommendation:"Define de antemano qué alertas requieren actuar de inmediato y verifícalas desde el canal oficial."},
  axolotl:{sprite:"two",name:"Ajolote",title:"Eres un Ajolote",trait:"El Resiliente",strength:"Comprendes que prevenir no siempre basta y valoras poder conservar y recuperar tu información.",opportunity:"Un respaldo poco frecuente o nunca probado podría no servir justo cuando más lo necesitas.",recommendation:"Automatiza tus respaldos y comprueba periódicamente que puedas restaurar tus archivos."}
 };
 const result=animalResults[winningProfile.category as keyof typeof animalResults];
 const profileAffinity=Math.min(100,Math.round(winningProfile.score));
 const opportunityChecks=[
  {when:answers[11]!==2,opportunity:"Tus archivos importantes pueden quedar incompletos si dependes de copias manuales o dispersas.",recommendation:"Configura un respaldo automático y comprueba que puedas recuperar una fotografía o documento."},
  {when:answers[4]!==2,opportunity:"Algunas de tus cuentas todavía podrían depender de una sola barrera o tener protección desigual.",recommendation:"Activa la verificación en dos pasos en tu correo, mensajería, redes y cuentas financieras."},
  {when:answers[5]!==0,opportunity:"Posponer actualizaciones puede dejar abiertas fallas que ya cuentan con una solución.",recommendation:"Programa las actualizaciones para el mismo día y activa su instalación automática cuando sea posible."},
  {when:answers[6]===1,opportunity:"Aceptar permisos para probar una aplicación puede darle acceso a más información de la necesaria.",recommendation:"Revisa cámara, micrófono, ubicación, contactos y galería antes de comenzar a utilizar cada aplicación."},
  {when:[0,2].includes(answers[1])||[0,2].includes(answers[9]),opportunity:"Las señales de familiaridad pueden hacer que una solicitud parezca legítima antes de estar confirmada.",recommendation:"Verifica llamadas, audios y solicitudes urgentes mediante un número o canal que tú ya conozcas."},
  {when:answers[10]!==0,opportunity:"Esperar ante un acceso desconocido puede darle más tiempo a otra persona para conservar el control.",recommendation:"Revisa inmediatamente las sesiones abiertas y cambia la contraseña si no reconoces el acceso."},
  {when:answers[8]===2,opportunity:"Confirmar el nombre de una Wi-Fi no evita todos los riesgos al realizar actividades sensibles.",recommendation:"Para banca, compras o información privada, cambia a tus datos móviles o a una red de confianza."}
 ];
 const personalized=opportunityChecks.find(item=>item.when);
 const resultOpportunity=personalized?.opportunity??result.opportunity;
 const resultRecommendation=personalized?.recommendation??result.recommendation;
 const assetBase="./";
 const shareSlugs={pigeon:"paloma",raccoon:"mapache",hedgehog:"erizo",dog:"perro",turtle:"tortuga",sloth:"perezoso",owl:"buho",axolotl:"ajolote"};
 const shareSlug=shareSlugs[winningProfile.category as keyof typeof shareSlugs];
 const shareUrl=`https://andrea-xeag.github.io/protege-tu-vida-digital/resultados/${shareSlug}/`;
 const shareText=`${result.title}: ${result.trait}. ¿Qué animal de seguridad digital eres?`;
 async function shareAnimal(){
  if(navigator.share){try{await navigator.share({title:result.title,text:shareText,url:shareUrl});return}catch(error){if(error instanceof DOMException&&error.name==="AbortError")return}}
  window.open(`https://wa.me/?text=${encodeURIComponent(`${shareText}\n${shareUrl}`)}`,"_blank","noopener,noreferrer");
 }
 async function copyShareLink(){await navigator.clipboard.writeText(shareUrl);setCopied(true);window.setTimeout(()=>setCopied(false),2500)}
 return <main>
  <header className="topbar"><a className="brand" href="#inicio"><span className="brand-mark"><LockKeyhole size={20}/></span><span>Protege tu <b>vida digital</b></span></a><nav aria-label="Navegación principal"><a href="#materiales">Recursos</a><a href="#quiz">Quiz</a><a href="#senales">Detecta estafas</a><a className="nav-quiz" href="#habitos">Protégete</a></nav></header>
  <section className="hero" id="inicio">
   <div className="hero-copy"><p className="material-tag">RECURSO 1 DE 4 · BANNER DIGITAL</p><p className="eyebrow"><span/>Tu información vale. Protégela.</p><h1>¿Eres blanco fácil para los <em>hackers</em>? Averígualo en 12 preguntas</h1><p className="lead">Quiz de 12 preguntas <b>GRATUITO</b> para saber cuál es tu animal de seguridad digital.</p><a className="primary" href="#materiales">Quiz GRATUITO <ArrowRight size={20}/></a><p className="safe-note"><ShieldCheck size={17}/>Detente. Verifica. Protege.</p></div>
   <div className="hero-visual"><img src={`${assetBase}hero-security-animals.webp`} alt="Mensaje bancario sospechoso rodeado por animales de seguridad digital"/></div>
  </section>
  <section className="materials-map" id="materiales" aria-label="Recursos de la campaña"><p>Esta campaña busca que conozcas mejor tu seguridad digital y puedas navegar de una manera más segura.</p><div><a href="#inicio"><span>01</span>Banner</a><a href="#quiz"><span>02</span>¿Qué tan fácil sería engañarte?</a><a href="#senales"><span>03</span>Señales de que estás frente a una estafa digital</a><a href="#habitos"><span>04</span>5 hábitos para proteger tu información</a></div></section>

  <section className="quiz-section" id="quiz"><div className="section-intro"><p className="material-tag light">RECURSO 2 DE 4 · QUIZ DE EVALUACIÓN</p></div>
   <div className="quiz-shell">
   {!started?<div className="quiz-welcome"><div className="big-shield"><ShieldCheck size={58}/></div><div><span className="mini-label">12 SITUACIONES · 8 ANIMALES DE SEGURIDAD</span><h3>Inicia el Quiz Gratis aquí</h3><p>No hay respuestas perfectas. Elige la opción que más se parezca a lo que realmente harías, no a lo que crees que deberías hacer.</p><button className="primary" onClick={()=>setStarted(true)}>Iniciar quiz <ChevronRight size={21}/></button></div></div>
   :done?<div className="result"><div className={`animal-portrait sprite-${result.sprite} ${winningProfile.category}`} style={{backgroundImage:`url(${assetBase}animal-results-${result.sprite}.webp)`}} role="img" aria-label={`Ilustración de ${result.name}`}/><p className="mini-label">TU PERFIL DE COMPORTAMIENTO DIGITAL · {profileAffinity}% DE AFINIDAD</p><h3>{result.title}</h3><h4>{result.trait}</h4><div className="profile-insights"><article className="strength"><b>Tu fortaleza</b><p>{result.strength}</p></article><article className="opportunity"><b>Tu área de oportunidad</b><p>{resultOpportunity}</p></article><article className="recommendation"><b>Tu siguiente paso</b><p>{resultRecommendation}</p></article></div><div className="share-result"><p>Comparte tu animal e invita a alguien a descubrir el suyo.</p><div className="share-actions"><button className="share-primary" onClick={shareAnimal}><Share2 size={19}/>Compartir mi animal</button><button className="share-copy" onClick={copyShareLink}><Copy size={18}/>{copied?"¡Enlace copiado!":"Copiar enlace"}</button></div></div><div className="survey result-survey"><p className="mini-label">TU OPINIÓN TAMBIÉN CUENTA</p><h3>Cuéntanos qué animal de seguridad eres</h3><p>Ahora que conoces tu resultado, ayúdanos dejando un comentario en este breve formulario.</p><iframe src="https://docs.google.com/forms/d/e/1FAIpQLSdVlpiZOhdv8jcaMHseabzMs9kikyS7ddIJCNGBT2aLJzG4Hg/viewform?embedded=true" title="Formulario de comentarios sobre la campaña">Cargando…</iframe></div><button className="secondary" onClick={restart}><RotateCcw size={19}/>Volver a intentarlo</button></div>
   :<div className="question-view"><div className="quiz-progress"><span>Pregunta {current+1} de {questions.length}</span><div><i style={{width:`${((current+1)/questions.length)*100}%`}}/></div></div><div className="message-card"><div className="message-meta"><span><MessageCircleWarning size={18}/>{q.channel}</span><small>{q.from}</small></div><p>“{q.text}”</p></div><h3>{q.prompt}</h3><div className="answers">{q.options.map((option,i)=><button key={option} className={selected===i?"selected":""} onClick={()=>choose(i)} disabled={selected!==null}><span>{String.fromCharCode(65+i)}</span>{option}</button>)}</div>{selected!==null&&<div className="answer-confirmation"><span>Respuesta guardada</span><button onClick={next}>{current===questions.length-1?"Ver mi resultado":"Siguiente pregunta"}<ArrowRight size={18}/></button></div>}</div>}
   </div>
  </section>

  <section className="signals" id="senales"><div className="section-intro left"><p className="material-tag">RECURSO 3 DE 4 · CARRUSEL INFORMATIVO</p><p className="kicker">Situaciones que pueden afectar tu vida digital</p><h2>Señales de que estás frente a una estafa digital</h2><p>Conoce cómo actúan los delincuentes, qué consecuencias puede tener caer en la trampa y cómo protegerte.</p></div><div className="carousel">
   {signals.map(({number,icon:Icon,title,attack,consequence,action},i)=><article key={title} className={i===slide?"active":""} aria-hidden={i!==slide}><div className="slide-count">{number} / 10</div><div className="slide-icon"><Icon/></div><h3>{title}</h3><div className="threat-block"><b>Lo que hace el atacante</b><p>{attack}</p></div><div className="consequence-block"><b>Si caes en la trampa</b><p>{consequence}</p></div><div className="slide-action"><ShieldCheck size={23}/><span><b>Qué hacer:</b> {action}</span></div></article>)}
   <div className="carousel-controls"><button onClick={()=>setSlide((slide+signals.length-1)%signals.length)} aria-label="Señal anterior">←</button><div>{signals.map((_,i)=><button key={i} className={i===slide?"active":""} onClick={()=>setSlide(i)} aria-label={`Ver señal ${i+1}`}/>)}</div><button onClick={()=>setSlide((slide+1)%signals.length)} aria-label="Siguiente señal">→</button></div>
  </div></section>

  <section className="habits" id="habitos"><div className="habits-head"><p className="material-tag">RECURSO 4 DE 4 · INFOGRAFÍA DIGITAL</p><p className="kicker">5 hábitos para proteger tu información</p><h2>Un mensaje falso puede robarte una cuenta, tus datos o tu dinero.</h2></div><div className="habit-list">{habits.map(({icon:Icon,title,text},i)=><article key={title}><span>{i+1}</span><Icon/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
  <section className="reaction"><div className="reaction-title"><p className="kicker">¿Ya abriste el enlace o compartiste información?</p><h2>Actúa de inmediato.</h2><p>Reaccionar rápido también forma parte de protegerte.</p></div><ol><li><span>1</span><div><b>Cambia tus contraseñas</b><p>Empieza por el correo y las cuentas financieras.</p></div></li><li><span>2</span><div><b>Contacta a la institución</b><p>Usa únicamente su aplicación, sitio o teléfono oficial.</p></div></li><li><span>3</span><div><b>Revisa movimientos y sesiones</b><p>Cierra accesos desconocidos y reporta cualquier cargo.</p></div></li><li><span>4</span><div><b>Avisa a tus contactos</b><p>Hazlo si pudieron suplantar tu identidad o tomar tu cuenta.</p></div></li></ol></section>
  <section className="closing"><ShieldCheck/><div><p>Antes de compartir, abrir o responder:</p><h2>Detente. Verifica. Protege.</h2></div><a href="#quiz" onClick={restart}>Repetir el reto <ArrowRight size={19}/></a></section>
  <footer><div className="brand"><span className="brand-mark"><LockKeyhole size={18}/></span><span>Protege tu <b>vida digital</b></span></div><p>Campaña de sensibilización sobre ciberseguridad · Tu información vale. Protege tu vida digital.</p></footer>
 </main>
}
